apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: netmaker
  name: netmaker
spec:
  replicas: 1
  serviceName: netmaker-headless
  selector:
    matchLabels:
      app: netmaker
  template:
    metadata:
      labels:
        app: netmaker
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args: ["sysctl -w net.ipv4.ip_forward=1 && sysctl -w net.ipv4.conf.all.src_valid_mark=1 && sysctl -w net.ipv6.conf.all.disable_ipv6=0 && sysctl -w net.ipv6.conf.all.forwarding=1"]
        securityContext:
          privileged: true
      dnsPolicy: ClusterFirstWithHostNet
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - netmaker
            topologyKey: "kubernetes.io/hostname"
      containers:
      - env:
        - name: SERVER_NAME
          value: broker.nm.k8s.clustercat.com
        - name: SERVER_API_CONN_STRING
          value: api.nm.k8s.clustercat.com:443
        - name: SERVER_HTTP_HOST
          value: api.nm.k8s.clustercat.com
        - name: API_PORT
          value: "8081"
        - name: WG_QUICK_USERSPACE_IMPLEMENTATION
          value: wireguard-go
        - name: DNS_MODE
          value: "off"
        - name: CLIENT_MODE
          value: "on"
        - name: DISPLAY_KEYS
          value: "on"
        - name: DATABASE
          value: sqlite
        - name: MASTER_KEY
          value: cqYXwQGWiLKj
        - name: PLATFORM
          value: Kubernetes
        - name: CORS_ALLOWED_ORIGIN
          value: '*'
        - name: MQ_HOST
          value: "mq"
        - name: MQ_PORT
          value: "31883"
        - name: PLATFORM
          value: "Kubernetes"
        - name: VERBOSITY
          value: "3"
        image: gravitl/netmaker:v0.14.3
        imagePullPolicy: Always
        name: netmaker
        ports:
        - containerPort: 8081
          protocol: TCP
        - containerPort: 31821
          protocol: UDP
        - containerPort: 31822
          protocol: UDP
        - containerPort: 31823
          protocol: UDP
        - containerPort: 31824
          protocol: UDP
        - containerPort: 31825
          protocol: UDP
        - containerPort: 31826
          protocol: UDP
        - containerPort: 31827
          protocol: UDP
        - containerPort: 31828
          protocol: UDP
        - containerPort: 31829
          protocol: UDP
        - containerPort: 31830
          protocol: UDP
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - NET_RAW
            - SYS_MODULE
        volumeMounts:
        - mountPath: /etc/netmaker/
          name: shared-certs
        - mountPath: /root/data
          name: netmaker-data
      volumes:
      - name: shared-certs
        persistentVolumeClaim:
          claimName: shared-certs-pvc
      - name: netmaker-data
        persistentVolumeClaim:
          claimName: netmaker-data-pvc
