---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: netmaker
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: netmaker-rqlite
  annotations:
    nfs.io/storage-path: "data01/netmaker/rqlite"
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
