version: "3.4"

services:
  mq:
    container_name: mq
    image: emqx/emqx:5.0.9
    restart: unless-stopped
    environment:
      - EMQX_NAME: "emqx"
      - EMQX_DASHBOARD__DEFAULT_PASSWORD=${MQ_PASSWORD}
      - EMQX_DASHBOARD__DEFAULT_USERNAME=${MQ_USERNAME}
    ports:
      - "1883:1883" # MQTT
      - "8883:8883" # SSL MQTT
      - "8083:8083" # Websockets
      - "18083:18083" # Dashboard/REST_API

