apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: netmaker
  name: netmaker
spec:
  replicas: 3
  serviceName: netmaker-headless
  selector:
    matchLabels:
      app: netmaker
  template:
    metadata:
      labels:
        app: netmaker
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - netmaker
            topologyKey: "kubernetes.io/hostname"
      containers:
      - env:
        - name: NODE_ID
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: SERVER_NAME
          value: NETMAKER_SUBDOMAIN
        - name: BROKER_NAME
          value: broker.NETMAKER_SUBDOMAIN
        - name: STUN_DOMAIN
          value: st.NETMAKER_SUBDOMAIN
        - name: SERVER_API_CONN_STRING
          value: api.NETMAKER_SUBDOMAIN:443
        - name: SERVER_HTTP_HOST
          value: api.NETMAKER_SUBDOMAIN
        - name: API_PORT
          value: "8081"
        - name: WG_QUICK_USERSPACE_IMPLEMENTATION
          value: wireguard-go
        - name: DNS_MODE
          value: "off"
        - name: DISPLAY_KEYS
          value: "on"
        - name: DATABASE
          value: postgres
        - name: SQL_HOST
          value: "DB_NAME-postgresql" 
        - name: SQL_PORT
          value: "5432"
        - name: SQL_DB
          value: "postgres"
        - name: SQL_USER
          value: "postgres"
        - name: SQL_PASS
          value: "DB_PASS"
        - name: MASTER_KEY
          value: REPLACE_MASTER_KEY
        - name: CORS_ALLOWED_ORIGIN
          value: '*'
        - name: MQ_HOST
          value: "mq"
        - name: MQ_PORT
          value: "443"
        - name: MQ_SERVER_PORT
          value: "1883"
        - name: STUN_PORT
          value: "33478"          
        - name: PLATFORM
          value: "Kubernetes"
        - name: VERBOSITY
          value: "3"
        - name: MQ_USERNAME
          value: "REPLACE_MQ_USERNAME"
        - name: MQ_PASSWORD
          value: "REPLACE_MQ_PASSWORD"
        image: gravitl/netmaker:v0.18.0
        imagePullPolicy: Always
        name: netmaker
        ports:
        - containerPort: 8081
          protocol: TCP
        - containerPort: 3478
          protocol: UDP
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: 'netmaker-stun'
spec:
  externalTrafficPolicy: Local
  type: NodePort
  ports:
  - port: 33478
    nodePort: 33478
    protocol: UDP
    targetPort: 33478
    name: stun-port
  selector:
    app: 'netmaker'
---
apiVersion: v1
kind: Service
metadata:
  name: 'netmaker-rest'
spec:
  ports:
  - name: rest
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: 'netmaker'
  sessionAffinity: None
  type: ClusterIP
# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: nm-api-ingress-nginx
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
#     cert-manager.io/cluster-issuer: "letsencrypt-nginx"
#     nginx.ingress.kubernetes.io/ssl-redirect: 'true'
# spec:
#   ingressClassName: nginx
#   tls:
#   - hosts:
#     - api.NETMAKER_SUBDOMAIN
#     secretName: nm-api-tls
#   rules:
#   - host: api.NETMAKER_SUBDOMAIN
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: netmaker-rest
#             port:
#               number: 8081
